### ISSUE TITLE
won t rename accross different partitions

### ISSUE THREAD

**Issue by mh-cbon** [andyburke/node-storehouse#8]
Hi,

at 
https://github.com/andyburke/node-storehouse/blob/master/storehouse.js#L372

beware that fs.rename will fail if the temporary folder and the destination folder are not on the same partition.

See : 
- http://stackoverflow.com/questions/21071303/node-js-exdev-rename-error
- https://github.com/nodejs/node-v0.x-archive/issues/2703

Alternate code,
```js
function moveToDestination( source, dest, then ) {
  var error;
  fs.createReadStream(source)
  .pipe(fs.createWriteStream(dest))
  .on('error', function (e) {
    error = e;
  }).on('close', function () {
    var err;
    if ( error )
      err = {
        error: 'error moving file',
        message: error,
        code: 500
      };
    then(err);
  })
}
```

**Comment by andyburke** [comment]
I've published a new version that will try to fall back to streams if the rename fails. Please check it out and re-open this issue if it does not resolve your problem.
