### ISSUE TITLE
fatal: reference is not a tree: e3e123e9af7c0829a6c1417d911572a75b4a5f95

### ISSUE THREAD

**Issue by ali-abbas-10p** [andyburke/node-storehouse#9]
When I am executing this command `npm install storehouse` i am getting following error.

code 128
npm ERR! Command failed: /usr/bin/git checkout e3e123e9af7c0829a6c1417d911572a75b4a5f95
npm ERR! fatal: reference is not a tree: e3e123e9af7c0829a6c1417d911572a75b4a5f95
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ali/.npm/_logs/2018-01-26T10_16_46_141Z-debug.log

**Comment by ali-abbas-10p** [comment]
Can anyone please guide how to fix it?

**Comment by andyburke** [comment]
That looks like it would be related to some deep dependency relying on a git-sourced dependency.

Unfortunately, I have not used this module in a while, so it's not very maintained. Are you still seeing the issue?
